

@startuml Komponenten

left to right direction

package com.acme.kurs #DDDDDD {
    package rest <<boundary>> #FFFFFF {
        [@RestController\nKursReadController] as KursReadController
    }

    package service <<control>> #FFFFFF {
        [@Service\nKursReadService] as KursReadService
    }

    package entity <<entity>> #FFFFFF {
        [Kurs]
    }
}

RESTClient ~~> [KursReadController]

[KursReadController] o--> [KursReadService]
[KursReadController] .up.> [Kurs]
[KursReadService] ..> [Kurs]

footer (c) Miguel Rasch

@enduml
