
= Projekthandbuch
Miguel Rasch
:doctype: book
:toc: left
:sectanchors:
:sectlinks:
:sectnums:
:pagenums:
:source-highlighter: rouge
:icons: font

// https://github.com/asciidoctor/asciidoctorj
// https://github.com/asciidoctor/asciidoctor-diagram
// http://de.plantuml.com/classes.html
// http://de.plantuml.com/component.html
// https://github.com/odrotbohm/asciidoctor-plantuml


== Der Microservice Kurs

=== Der Microservice im Überblick

bla bla

.Use Cases für den Microservice "kurs"
[plantuml,use-cases,svg]
----
include::./use-cases.plantuml[]
----

bla bla

.Komponenten des Microservice "kurs"
[plantuml,komponenten,svg]
----
include::./komponenten.plantuml[]
----

=== Die REST-Schnittstelle

bla bla

."KursGetController" für Lesezugriffe an der REST-Schnittstelle
[plantuml,KursGetController,svg]
----
include::./KursGetController.plantuml[]
----

."Sequenzdiagramm" mit den Methodenaufrufen
[plantuml,sequenzdiagramm,svg]
----
include::sequenzdiagramm.plantuml[]
----

."KursWriteController" für Schreibzugriffe an der REST-Schnittstelle
[plantuml,KursWriteController,svg]
----
include::./KursWriteController.plantuml[]
----

=== Die Geschäftslogik

bla bla

.Die Service-Klasse "KursReadService" für die Geschäftslogik
[plantuml,KursReadService,svg]
----
include::./KursReadService.plantuml[]
----

bla bla

.Die Service-Klasse "KursWriteService" für die Geschäftslogik
[plantuml,KursWriteService,svg]
----
include::./KursWriteService.plantuml[]
----

=== Die Entity-Klassen

bla bla

.Die Entity-Klasse "Kurs" für Kursdaten
[plantuml,Kurs,svg]
----
include::./Kurs.plantuml[]
----

== Programmierrichtlinien

TIP: Als Studierende/r sollte man sich frühzeitig an Programmierrichtlinien
     gewöhnen. Das hinterlässt im späteren Praxissemester einen professionellen Eindruck.

=== Java

[horizontal]
_Oracle_:: https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html
_Google_:: https://google.github.io/styleguide/javaguide.html
_Microsoft Azure_:: https://azure.github.io/azure-sdk/java_introduction.html
_Mozilla_:: https://firefox-source-docs.mozilla.org/code-quality/coding-style/coding_style_java.html

=== SQL

[horizontal]
_SQL_:: https://www.sqlstyle.guide

=== TypeScript und JavaScript

[horizontal]
_Microsoft_:: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines
_Angular_:: https://angular.io/docs/ts/latest/guide/style-guide.html
_Airbnb_:: https://github.com/airbnb/javascript
_React bei Airbnb_:: https://github.com/airbnb/javascript/tree/master/react

=== Python

[horizontal]
_Google_:: https://google.github.io/styleguide/pyguide.html

=== Kotlin

Für die Entwicklung mit *Kotlin* sind folgende Styleguides empfehlenswert:

[horizontal]
_Kotlin_:: https://kotlinlang.org/docs/reference/coding-conventions.html
_Android_:: https://developer.android.com/kotlin/style-guide
