@startuml Sequenzdiagramm

actor Client

boundary KursGetController
control KursReadService
control KursRepository

Client -> KursGetController : GET / getById()
KursGetController -> KursReadService: findById()
KursReadService -> KursRepository: findById()

footer (c) Miguel Rasch

@enduml
