
@startuml Use Cases

left to right direction

actor Gast
actor Kurs
actor Admin

rectangle kurs {
    Gast --> (registrieren)
    Kurs --> (Kurs suchen)
    Kurs --> (Kurs ändern)
    Admin --> (Kurs suchen)
    Admin --> (Kurs ändern)
    Admin --> (Kurs löschen)
}

footer (c) Miguel Rasch

@enduml
